import {TUser} from "@entities";

const getAll = (): Array<TUser> => {
    return [
        {
            id: '0000',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0001',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0002',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0003',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0004',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0005',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0006',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0007',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0008',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0009',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0010',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0011',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0012',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0013',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0014',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0015',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        }, {
            id: '0016',
            firstName: 'Name',
            lastName: 'Surname',
            patronymic: 'FatherName',
            email: 'email@email.com'
        },
    ]
}

export const userApi = {getAll}