export { AppContext, initialHotelData } from './appContext'
export type { IHotelData } from './appContext'
export { UserContext, initialUserData } from './userContext'
export type { TUserContext } from './userContext'
export { StyleContext } from './stylesContext'
export type { TStyleContext } from './stylesContext'
